"""Mock book catalogue used by ``scripts/seed.py`` and the test fixtures.

There is no real book dataset behind this template; this list stands in for one.
ISBNs are synthetic but unique.
"""

from __future__ import annotations

BOOKS: list[dict[str, object]] = [
    {
        "title": "The Left Hand of Darkness",
        "author": "Ursula K. Le Guin",
        "isbn": "9780441478125",
        "genre": "science fiction",
        "published_year": 1969,
        "price": 12.99,
        "in_stock": 14,
        "description": "An envoy on an icebound world where people have no fixed sex.",
    },
    {
        "title": "Kindred",
        "author": "Octavia E. Butler",
        "isbn": "9780807083697",
        "genre": "science fiction",
        "published_year": 1979,
        "price": 13.50,
        "in_stock": 9,
        "description": "A woman is pulled between 1976 California and an antebellum plantation.",
    },
    {
        "title": "The Name of the Rose",
        "author": "Umberto Eco",
        "isbn": "9780544176560",
        "genre": "mystery",
        "published_year": 1980,
        "price": 15.00,
        "in_stock": 6,
        "description": "A Franciscan friar investigates deaths in a 14th-century abbey.",
    },
    {
        "title": "Gödel, Escher, Bach",
        "author": "Douglas Hofstadter",
        "isbn": "9780465026562",
        "genre": "nonfiction",
        "published_year": 1979,
        "price": 22.95,
        "in_stock": 4,
        "description": "A meditation on minds, machines, and self-reference.",
    },
    {
        "title": "Beloved",
        "author": "Toni Morrison",
        "isbn": "9781400033416",
        "genre": "literary fiction",
        "published_year": 1987,
        "price": 14.00,
        "in_stock": 11,
        "description": "A formerly enslaved woman is haunted by the daughter she lost.",
    },
    {
        "title": "The Dispossessed",
        "author": "Ursula K. Le Guin",
        "isbn": "9780061054884",
        "genre": "science fiction",
        "published_year": 1974,
        "price": 12.99,
        "in_stock": 8,
        "description": "A physicist travels from an anarchist moon to the world it fled.",
    },
    {
        "title": "Never Let Me Go",
        "author": "Kazuo Ishiguro",
        "isbn": "9781400078776",
        "genre": "literary fiction",
        "published_year": 2005,
        "price": 16.00,
        "in_stock": 13,
        "description": "Students at an English boarding school learn what they were made for.",
    },
    {
        "title": "The Fifth Season",
        "author": "N. K. Jemisin",
        "isbn": "9780316229296",
        "genre": "fantasy",
        "published_year": 2015,
        "price": 17.99,
        "in_stock": 20,
        "description": "A mother searches for her daughter as the continent tears itself apart.",
    },
    {
        "title": "Piranesi",
        "author": "Susanna Clarke",
        "isbn": "9781635575637",
        "genre": "fantasy",
        "published_year": 2020,
        "price": 18.00,
        "in_stock": 15,
        "description": "A man lives in an endless house of tides and statues.",
    },
    {
        "title": "The Sixth Extinction",
        "author": "Elizabeth Kolbert",
        "isbn": "9781250062185",
        "genre": "nonfiction",
        "published_year": 2014,
        "price": 16.95,
        "in_stock": 7,
        "description": "A field report on the mass extinction humans are causing.",
    },
    {
        "title": "Snow Crash",
        "author": "Neal Stephenson",
        "isbn": "9780553380958",
        "genre": "science fiction",
        "published_year": 1992,
        "price": 15.99,
        "in_stock": 10,
        "description": "A pizza-delivering hacker chases a linguistic virus through the Metaverse.",
    },
    {
        "title": "The Goblin Emperor",
        "author": "Katherine Addison",
        "isbn": "9780765326997",
        "genre": "fantasy",
        "published_year": 2014,
        "price": 16.99,
        "in_stock": 12,
        "description": "A neglected half-goblin prince suddenly inherits a throne.",
    },
    {
        "title": "Station Eleven",
        "author": "Emily St. John Mandel",
        "isbn": "9780804172448",
        "genre": "literary fiction",
        "published_year": 2014,
        "price": 15.00,
        "in_stock": 18,
        "description": "A troupe of actors travels a world remade by a pandemic.",
    },
    {
        "title": "The Overstory",
        "author": "Richard Powers",
        "isbn": "9780393356687",
        "genre": "literary fiction",
        "published_year": 2018,
        "price": 18.95,
        "in_stock": 5,
        "description": "Nine strangers are drawn together by trees.",
    },
    {
        "title": "A Memory Called Empire",
        "author": "Arkady Martine",
        "isbn": "9781250186430",
        "genre": "science fiction",
        "published_year": 2019,
        "price": 17.99,
        "in_stock": 16,
        "description": "An ambassador carries her predecessor's memories into a hostile court.",
    },
    {
        "title": "The Haunting of Hill House",
        "author": "Shirley Jackson",
        "isbn": "9780143039983",
        "genre": "horror",
        "published_year": 1959,
        "price": 11.00,
        "in_stock": 9,
        "description": "Four people spend a summer in a house that is not sane.",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "isbn": "9780399590504",
        "genre": "memoir",
        "published_year": 2018,
        "price": 17.00,
        "in_stock": 22,
        "description": "A woman raised off the grid in Idaho makes her way to Cambridge.",
    },
    {
        "title": "The Three-Body Problem",
        "author": "Liu Cixin",
        "isbn": "9780765382030",
        "genre": "science fiction",
        "published_year": 2008,
        "price": 16.99,
        "in_stock": 19,
        "description": "A first-contact signal answered during the Cultural Revolution.",
    },
    {
        "title": "Circe",
        "author": "Madeline Miller",
        "isbn": "9780316556347",
        "genre": "fantasy",
        "published_year": 2018,
        "price": 16.99,
        "in_stock": 21,
        "description": "The witch of Aiaia tells her own story.",
    },
    {
        "title": "The Emperor of All Maladies",
        "author": "Siddhartha Mukherjee",
        "isbn": "9781439170915",
        "genre": "nonfiction",
        "published_year": 2010,
        "price": 20.00,
        "in_stock": 6,
        "description": "A biography of cancer, from ancient surgeons to modern oncology.",
    },
    {
        "title": "Recursion",
        "author": "Blake Crouch",
        "isbn": "9781524759780",
        "genre": "thriller",
        "published_year": 2019,
        "price": 15.99,
        "in_stock": 13,
        "description": "A detective and a scientist confront a technology that rewrites memory.",
    },
    {
        "title": "Braiding Sweetgrass",
        "author": "Robin Wall Kimmerer",
        "isbn": "9781571313560",
        "genre": "nonfiction",
        "published_year": 2013,
        "price": 18.00,
        "in_stock": 17,
        "description": "A botanist braids Indigenous knowledge with plant science.",
    },
    {
        "title": "The City & the City",
        "author": "China Miéville",
        "isbn": "9780345497526",
        "genre": "mystery",
        "published_year": 2009,
        "price": 16.00,
        "in_stock": 8,
        "description": "A murder spans two cities that occupy the same ground.",
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "isbn": "9780593135204",
        "genre": "science fiction",
        "published_year": 2021,
        "price": 18.99,
        "in_stock": 25,
        "description": "A lone astronaut wakes with amnesia on a mission to save the sun.",
    },
]
